### ISSUE TITLE
Trying to install plugin gives: Host key verification failed error

### ISSUE THREAD

**Issue by ahsath** [liamfiddler/eleventy-plugin-lazyimages#5]
```
✔︎ tomee-landing-page yarn add iamfiddler/eleventy-plugin-lazyimages -D
yarn add v1.22.1
[1/4] 🔍  Resolving packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads ssh://git@github.com/iamfiddler/eleventy-plugin-lazyimages.git
Directory: /Users/ahsath/Documents/repos/tomee-landing-page
Output:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by ahsath** [comment]
This only happens with Yarn

**Comment by liamfiddler** [comment]
Thanks for bringing this to my attention.

Looks like yarn is using SSH to read from the repo and your machine doesn't recognise GitHub's servers. You could try adding GitHub to the list of authorized hosts by following the instructions in this SO post: https://stackoverflow.com/a/29380765

But the easier solution is [install the package from npm](https://www.npmjs.com/package/eleventy-plugin-lazyimages) instead of GitHub by using `yarn add eleventy-plugin-lazyimages`

I've updated the readme with this info: https://github.com/liamfiddler/eleventy-plugin-lazyimages#install-the-plugin
