### ISSUE TITLE
Add Support To M1 Devices 

### ISSUE THREAD

**Issue by talmax1124** [liamfiddler/eleventy-plugin-lazyimages#51]
Current projects using this plugin in 11ty cannot be used because of the use of Sharp. Please upgrade the sharp version and update. @liamfiddler

**Comment by talmax1124** [comment]
Please approve this Push Request ~ https://github.com/liamfiddler/eleventy-plugin-lazyimages/pull/52 to allow support for newer devices. @liamfiddler

**Comment by talmax1124** [comment]
I would also recommend using one of these GitHub action to keep your packages updated: 

https://github.com/marketplace/actions/update-version-in-package-json
https://github.com/marketplace/actions/github-action-for-package-json-update
https://github.com/marketplace/actions/automated-version-bump
https://aboutbits.it/blog/2021-03-11-using-github-actions-to-perfom-npm-version-increment

**Comment by ixartz** [comment]
I got the same error, it doesn't work on mac due to sharp version

**Comment by talmax1124** [comment]
Even with the new sharp version? They told me they optimized the last version of sharp to be supported. Can you verify w/ the new pr I made @liamfiddler

**Comment by talmax1124** [comment]
I dont know if its up already on NPM. I know it takes some time. Can you give me permission to do pull requests on your repo. I'll make sure everything is compatible

**Comment by ixartz** [comment]
With the new sharp version, it's working. The old version doesn't work on mac m1.

**Comment by talmax1124** [comment]
& You should update the examples because to be honest, it gets annoying doing cd & npm installing every example

**Comment by talmax1124** [comment]
Can you check if its published in NPM so I can add it once again

**Comment by talmax1124** [comment]
& thanks @ixartz! How did you get it working locally?

**Comment by liamfiddler** [comment]
>Current projects using this plugin in 11ty cannot be used because of the use of Sharp. Please upgrade the sharp version and update.

Thanks for raising this, and for making the PR @talmax1124 

I don't have a M1, so it took me a few days to borrow a friend's machine and test it, but it's now been merged and published to npm 🎉  

>I would also recommend using one of these GitHub action to keep your packages updated

Great recommendations, thanks! I'll consider them.

> & You should update the examples because to be honest, it gets annoying doing cd & npm installing every example

This is an intentional choice.

I 100% agree it is annoying for _editors of the plugin_ to keep each example up-to-date, but the target audience for the examples are _users of the plugin_. For this group I've found it's valuable to have a minimal, self-contained example to point at, copy-paste as a starting point, and debug issues if something is going wrong in their project.

That said, if you have an idea to accommodate both groups a PR would be most welcome! 😃 

> How did you get it working locally?

The easiest way (that I know of) would be to install the package from GitHub instead of the npm registry using a command like `npm install --save username/repo#branch-name`.

So to try your forked version they might have used `npm install --save talmax1124/eleventy-plugin-lazyimages#master`

----

I'll close this issue because M1 support has been added in the latest release. Feel free to reach out if you have any further questions or issues.
